spring:
  application:
    name: uni-sport

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  profiles:
    active: local

#logging:
#  level:
#    uz.uniSport: DEBUG
#    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, metrics

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: ${PORT:9092}
  address: 0.0.0.0
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never


