spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
#
#minio:
#  url: ${MINIO_URL}
#  access-key: ${MINIO_ACCESS_KEY}
#  secret-key: ${MINIO_SECRET_KEY}
#  bucket-name: ${MINIO_BUCKET:unisport-files}

jwt:
  secret: ${JWT_SECRET}
  expiration-minutes: 15
  refresh-expiration-days: 7