spring:
  application:
    name: uni-sport

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
      active: local
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, metrics

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: ${PORT:9092}
  address: 0.0.0.0
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
ai:
  openai:
    api-key: ${OPENAI_API_KEY:}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}

  gemini:
    api-key: ${GEMINI_API_KEY:}
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent}